[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#3366ff"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#141b2d"

[browser]
gatherUsageStats = false
